expose:
 # type: LoadBalancer
  tls:
    enabled: false
  ingress:
    hosts:
      core: harbor.apps.oc.hci.com
      notary: notary.harbor.apps.oc.hci.com
    className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx

database:
  type: external
  external:
    host: "20.82.32.184"
    port: "5432"
    username: "postgres"
    password: "OCHcIDemo123"

externalURL: http://harbor.apps.oc.hci.com
persistence:
  enabled: false

logLevel: info

harborAdminPassword: "H@rb0rAdm12345"

secretKey: "not-a-secure-key"

chartmuseum:
  enabled: false

notary:
  enabled: false

trivy:
  enabled: false
